### ISSUE TITLE
create new API from bash script

### ISSUE THREAD

**Issue by kab1012** [FusionAuth/fusionauth-dart-client#12]
Hello @robotdan , I am a new user of fusion auth. I was trying the example shared on https://www.youtube.com/watch?v=xY_3Xnpqin8&ab_channel=FusionAuth but it was giving me the same "response". I am using the current version of the fusionauth and was making the example work on my local.

Any thoughts?

**Comment by jobannon** [comment]
@kab1012 This might be a good question to post in our forum for feedback and review as well.

https://fusionauth.io/community/forum/

**Comment by mooreds** [comment]
Closing this out as it is more suitable for the forum.
