### ISSUE TITLE
error in user registration

### ISSUE THREAD

**Issue by JenishEmpiric** [FusionAuth/fusionauth-dart-client#5]
i have getting error in user registration api

```
url = "https://fa.wajooba.xyz/api/user/registration"
method = "POST"

body : 
{
    "registration": {
        "applicationId": "-original app id-"
    },
    "user": {
        "email": "--email--",
        "firstName": "hdhdhdhd",
        "lastName": "xbxgdgdgd",
        "password": "Test@1234"
    }
}

header :  
X-FusionAuth-TenantId:--tenantid--
Content-Type:application/json


response : 
{
    "fieldErrors": {
        "": [
            {
                "code": "[invalidJSON]",
                "message": "Invalid JSON in the request body. The property was []. The error was [Possible conversion error]. The detailed exception was [No content to map due to end-of-input\n at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 1, column: 0]]."
            }
        ]
    }
}
```

**Comment by robotdan** [comment]
What version of FusionAuth are you using, and what version of the Dart client are you using?

**Comment by robotdan** [comment]
@JenishEmpiric were you able to resolve the issue or did you still need assistance?

**Comment by kunalbackers** [comment]
Hello @robotdan , I am a new user of fusion auth. I was trying the example shared on https://www.youtube.com/watch?v=xY_3Xnpqin8&ab_channel=FusionAuth but it was giving me the same "response". I am using the current version of the fusionauth and was making the example work on my local.

Any thoughts?

**Comment by facundorodriguez0** [comment]
Having the same issue using `@fusionauth/typescript-client`

**Comment by jobannon** [comment]
@kunalbackers 

Can you provide a bit more details about what you were having issues with?  Are using the dart client and trying to access the API to manage API's? (https://fusionauth.io/docs/v1/tech/apis/api-keys/)  

If so, perhaps a better spot to continue this conversation would be in a new issue (this is referencing the `user/registration` endpoint) or at our community forum (https://fusionauth.io/community/forum/) for community-supported troubleshooting.

**Comment by jainpawan21** [comment]
Hi, Is there any fix for this? I am also getting the same error with this Get API Request `/api/user/{userId}`

**Comment by mooreds** [comment]
@jainpawan21 if this is a bug, please open a new issue with detailed replication steps (feel free to reference this issue). The team at FusionAuth has been unable to replicate this issue and needs more details.
