### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by stellanhaglund** [FusionAuth/fusionauth-dart-client#7]
Hi there I just got this issue.

```
 result =
        await appAuth.authorizeAndExchangeCode(
          AuthorizationTokenRequest(
            FUSIONAUTH_CLIENTID,
            FUSIONAUTH_REDIRECT_URI,
//            issuer: FUSIONAUTH_ISSUER,
            discoveryUrl: FUSIONAUTH_DISCOVERY_URL,
            scopes: <String>['openid', 'profile', 'offline_access'],
            // promptValues: ['login']
          ),
        );```

I am getting thee error below
===================
PlatformException(authorize_and_exchange_code_failed, Failed to authorize:[error: invalid_client, description: Client
authentication missing aaas Basic Authorization header or credentials in the body(or some combination of them.], null, null)


```

found the solution here https://fusionauth.io/community/forum/topic/428/social-login-with-flutter-app
but I don't see that any issue has been filed.

what problems can disabling require authentition give?

**Comment by mooreds** [comment]
Hiya, thanks for using FusionAuth!

> what problems can disabling require authentication give?

@stellanhaglund this seems like a support request. If you have a support plan, please [open a ticket](https://account.fusionauth.io/account/support/). If you are on the community or developer plans, [please post in the forum](https://fusionauth.io/community/forum/).

We use github for tracking reproducible bugs, which this does not appear to be. Sorry about the hassle, we just want to be clear about where you go for support vs filing a bug.

Closing the issue.

**Comment by stellanhaglund** [comment]
The forum thread specifically said post an issue. 

And with the need to disable require authentication to be able to use this with app auth doesn't seem like a support request to me.

**Comment by mooreds** [comment]
Ah, maybe I was unclear in my forum post.

> "You could try turning off "Require authentication" in the application's OAuth tab and seeing if that helps."

Did that help

**Comment by mooreds** [comment]
If so, what I saw as a support request was "what are the ramifications of turning off client authentication"

If that didn't help, then it is a bug and we should continue the discussion here.

Cheers!

**Comment by stellanhaglund** [comment]
Yes that helped. 

> If that fixes it, it seems like the FusionAuth dart client isn't properly providing the client secret to FusionAuth, which seems like a bug. If so, can you file an issue here: https://github.com/fusionauth/fusionauth-dart-client

**Comment by stellanhaglund** [comment]
The implication question was more for me to understand if this makes my setup less secure until I don't need to have the require authentication disabled.

**Comment by mooreds** [comment]
@stellanhaglund Ah, thanks! I re-read my comment on the forum. I need to clarify some things (I was wrong).

I'll follow up in the next week or so with some pointers to updated docs, but the short answer is:

* You can't have a secure client secret on a mobile client (anyone can decompile the dart app you are writing).
* Application authentication requires a secure client secret.
* Therefore you need to turn it off for the authorization code grant to work.
* But to protect from certain attacks, you should use PKCE: https://github.com/FusionAuth/fusionauth-dart-client/blob/master/lib/src/FusionAuthClient.dart#L1070

More about the possible attack here: https://tools.ietf.org/html/rfc7636

Hope that helps. 

Will keep this issue open until I've updated the doc.

Sorry for the confusion on my part!

**Comment by mooreds** [comment]
OK, I updated the documentation in this PR: https://github.com/FusionAuth/fusionauth-site/pull/552 which was just deployed.
